// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5JHkysQhPIWx0P9hw23QwLEk1NEFMxhk',
    appId: '1:604575451488:web:ae58dd1c77a6d3db23b605',
    messagingSenderId: '604575451488',
    projectId: 'suzyapp',
    authDomain: 'suzyapp.firebaseapp.com',
    storageBucket: 'suzyapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4r5hjKv79dc3bqJvew0nVEe7KZRCPpHM',
    appId: '1:604575451488:android:987d6a1f3bdcc7cd23b605',
    messagingSenderId: '604575451488',
    projectId: 'suzyapp',
    storageBucket: 'suzyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37cJd8OwJBMqSrSq2VvL3I1LA1fMc5OY',
    appId: '1:604575451488:ios:97381720ea056ae223b605',
    messagingSenderId: '604575451488',
    projectId: 'suzyapp',
    storageBucket: 'suzyapp.firebasestorage.app',
    iosBundleId: 'com.example.suzyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD37cJd8OwJBMqSrSq2VvL3I1LA1fMc5OY',
    appId: '1:604575451488:ios:97381720ea056ae223b605',
    messagingSenderId: '604575451488',
    projectId: 'suzyapp',
    storageBucket: 'suzyapp.firebasestorage.app',
    iosBundleId: 'com.example.suzyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5JHkysQhPIWx0P9hw23QwLEk1NEFMxhk',
    appId: '1:604575451488:web:1da2230ce12c52f923b605',
    messagingSenderId: '604575451488',
    projectId: 'suzyapp',
    authDomain: 'suzyapp.firebaseapp.com',
    storageBucket: 'suzyapp.firebasestorage.app',
  );
}
